"""Immutable bundles and exact-first comparison for adapter equivalence."""

from .bundle_capture import (
    PerformanceRecorder,
    build_provenance,
    capture_control,
    capture_generation,
    normalize_expected_error,
    publish_bundle,
)
from .compare import (
    ComparisonMismatch,
    ComparisonReport,
    compare_bundles,
)
from .fixtures import (
    AdapterFixture,
    FixtureValidationError,
    MatrixCell,
    build_lora_fixture,
    build_oft_fixture,
    validate_matrix,
)
from .schema import (
    SCHEMA_VERSION,
    BaselineRepetition,
    BundleValidationError,
    CaseKey,
    ComparisonPolicy,
    NumericTolerance,
    Observation,
    PerformanceMetrics,
    RunBundle,
    ToleranceEnvelope,
    canonical_sha256,
)
from .server import (
    AdapterControl,
    AdapterIdentity,
    BaseControl,
    ControlResult,
    DistributedPayload,
    NativeLoRAControl,
    NativeOFTControl,
    make_adapter_control,
    normalize_control_result,
)
from .stress_case import StressResult, StressSpec, run_stress

__all__ = [
    "SCHEMA_VERSION",
    "AdapterControl",
    "AdapterFixture",
    "AdapterIdentity",
    "BaselineRepetition",
    "BaseControl",
    "BundleValidationError",
    "CaseKey",
    "ComparisonMismatch",
    "ComparisonReport",
    "ComparisonPolicy",
    "ControlResult",
    "DistributedPayload",
    "FixtureValidationError",
    "MatrixCell",
    "NativeLoRAControl",
    "NativeOFTControl",
    "NumericTolerance",
    "Observation",
    "PerformanceRecorder",
    "PerformanceMetrics",
    "RunBundle",
    "StressResult",
    "StressSpec",
    "ToleranceEnvelope",
    "canonical_sha256",
    "build_provenance",
    "build_lora_fixture",
    "build_oft_fixture",
    "capture_control",
    "capture_generation",
    "compare_bundles",
    "make_adapter_control",
    "normalize_control_result",
    "normalize_expected_error",
    "publish_bundle",
    "run_stress",
    "validate_matrix",
]
